"""add_category_tags_to_favorites

Revision ID: f01eefa8f00b
Revises: d67d120736fb
Create Date: 2026-03-31 19:38:01.834757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01eefa8f00b'
down_revision: Union[str, None] = 'd67d120736fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('category_tags', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'category_tags')
    # ### end Alembic commands ###
